Added support for model files

diff --git a/new b/new
--- a/new
+++ b/new
@@ -21,7 +21,7 @@
 #
 
 loc=~/.new
-default=index.sh
+default=index
 
 function printHelp() {
 	# Help Display
@@ -66,6 +66,7 @@ wether the file already has an extension"
 MAIN_EXTENSION=""
 BUILDER="${default}"
 BUILDER_EXTENSIONS=( "" ".sh" ".py" )
+MODEL_EXTENSIONS=(".txt")
 PARAMETERS=""
 FILE_LIST=()
 EXTENSION_LIST=()
@@ -219,20 +220,34 @@ else
 			continue
 		fi
 
+		# generate file
 		builder_found=0
+		# find builder
 		for build_extension in "${BUILDER_EXTENSIONS[@]}"; do
 			if [ -f "$loc/$extension/$default$build_extension" ]; then
 				output="$("$loc/$extension/$default$build_extension" "$filename" "$loc/$extension")"
 				if [ ! $? ]; then
+					echo "Builder error for file '$filename' :" >&2
+					echo "$output" >&2
 					file_builder_errors=$[file_builder_errors+1]
 				fi
 				builder_found=1
 				break
 			fi
 		done
+		# find model if no builder was found
+		if [ $builder_found -eq 0 ]; then
+			for model_extension in "${MODEL_EXTENSIONS[@]}"; do
+				if [ -f "$loc/$extension/$default$model_extension" ]; then
+					cp "$loc/$extension/$default$model_extension" "$filename"
+					[ -x "$filename" ] && chmod 755 "$filename" || chmod 644 "$filename"
+					builder_found=1
+				fi
+			done
+		fi
 
 		if [ $builder_found -eq 0 ]; then
-			echo "Could not find builder named $default for $filename" >&2
+			echo "Could not find builder or model named $default for $filename" >&2
 			file_not_generated=$[file_not_generated+1]
 		fi
 
@@ -245,3 +260,4 @@ fi
 if [ $file_builder_errors -ne 0 ]; then
 	exit 12
 fi
+
